### ISSUE TITLE
Duplicate layer

### ISSUE THREAD

**Issue by cosminstefanxp** [EtienneK/spring-boot-docker-base#1]
It seems that due to the `touch ${BOOTAPP_PATH}` command in the Dockerfile, an extra layer with the app size is created, as it can be seen in the history:
```
72a0755d3003        8 minutes ago       /bin/sh -c #(nop)  USER bootapp                 0B
a94d329e0707        8 minutes ago       |1 JAR_FILE=app.jar /bin/sh -c chmod 555 ${B…   105MB
a0ad70f84000        8 minutes ago       /bin/sh -c #(nop) COPY file:fb19d7e72a1fd509…   105MB
5ea40283ae2d        8 minutes ago       /bin/sh -c #(nop)  USER root                    0B
b8850db2ae57        8 minutes ago       /bin/sh -c #(nop)  ARG JAR_FILE=app.jar         0B
c9808f487b31        5 months ago        /bin/sh -c #(nop)  ENTRYPOINT ["/wrapper.sh"]   0B
...
```

Is that step necessary? Could we optimize it somehow?

**Comment by EtienneK** [comment]
Yeah, the touch isn't needed anymore.

Previous versions of docker didn't set the modified date of copied files. And for some static files in a Spring Boot app it is required (example: index.html for checking for cache invalidation).

We can remove it, but there is no point as we still need the "chmod" on that line. Removing just the "touch" piece still produces a duplicate layer.

Until docker implements https://github.com/moby/moby/issues/34819 we will have to keep that line.

**Comment by cosminstefanxp** [comment]
Alright, thanks for the explanation.
